services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: tiny-url-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - tiny-url-db-vol:/var/lib/mysql

  be:
    build:
      context: .
      dockerfile: beDockerfile
    container_name: tiny-url-be
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - db

volumes:
  tiny-url-db-vol:
