services:
  db:
    image: mysql:8.0
    container_name: tiny-url-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - tiny-url-db-vol:/var/lib/mysql

  be:
    build:
      context: .
      dockerfile: be-dockerfile-dev
    container_name: tiny-url-be
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ./be:/usr/app/be
    depends_on:
      - db

  fe:
    build:
      context: .
      dockerfile: fe-dockerfile-dev
    container_name: tiny-url-fe
    restart: always
    ports:
      - 4444:4444
    volumes:
      - ./fe:/usr/app/fe
    depends_on:
      - be

volumes:
  tiny-url-db-vol:
